### PR TITLE
Now using ESLint

### LINKED ISSUE #56: Possible bug in QueueWorker.prototype._reject
QueueWorker.prototype._reject creates a function that takes a parameter "error".
The transaction complete handler masks "error" with its own "error" which is passed to the recursive attempt upon failure.

I would expect the behavior to keep trying to log the original error instead of the failed transaction attempt.

Is this intended or just a bug?

### PR DESCRIPTION
**Pull request by drtriumph**
Fixes #56 and generally tidies up the code

Best viewed with ?w=1 to remove whitespace changes

### CODE REVIEW

File: src/queue.js [hunk 1]
```diff
@@ -8,18 +8,18 @@
...
+var RSVP = require('rsvp');
+var logger = require('winston');
+var QueueWorker = require('./lib/queue_worker.js');
+
+var DEFAULT_NUM_WORKERS = 1;
+var DEFAULT_SANITIZE = true;
+var DEFAULT_SUPPRESS_STACK = false;
+var DEFAULT_TASK_SPEC = {
+  inProgressState: 'in_progress',
+  timeout: 300000 // 5 minute;
```
Comment (mbleigh) [inline src/queue.js]: I don't think you need a `;` in your comment, and should be `5 minutes`

**Comment by mbleigh** [comment]
One comment typo nit, otherwise LGTM. Feel free to merge after fixing comment.
